[package]
name = "desktop"
version = "0.1.0"
edition = "2021"
authors = ["materight"]

[dependencies]
gb-core = { path = "../core" }

clap = { version = "4.5.1", features = ["derive"] }
minifb = "0.25"
